#!/usr/bin/env bash

set -e
if [[ $* == *-y* ]]; then 
    sudo nixos-rebuild switch --flake ~/.dotfiles#work
    exit 0
fi

cd  ~/.dotfiles
git add .
code . -w -n
if [[ $* != *-n* ]]; then 
    sudo nixos-rebuild switch --flake ~/.dotfiles#work
fi
